export const FETCH_WEATHER_START = 'FETCH_WEATHER_START'
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE'
export const FETCH_COORDS_SUCCESS = 'FETCH_COORDS_SUCCESS'

export const SET_ERROR = 'SET_ERROR'

export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS'
export const FETCH_FORECAST_FAILURE = 'FETCH_FORECAST_FAILURE'