export const FETCH_WEATHER_START = 'FETCH_WEATHER_START'
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE'

export const SET_ERROR = 'SET_ERROR'
export const SET_COORDS = 'SET_COORDS'
export const SET_DATA = 'SET_DATA'
export const SET_FORECAST_DATA = 'SET_DATA'
export const SET_LOADING = 'SET_LOADING'

export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS'
export const FETCH_FORECAST_FAILURE = 'FETCH_FORECAST_FAILURE'

export const FETCH_WEATHER_BY_NAME_SUCCESS = 'FETCH_WEATHER_BY_NAME_SUCCESS'
export const FETCH_WEATHER_BY_NAME_FAILURE = 'FETCH_WEATHER_BY_NAME_FAILURE'

export const FETCH_FORECAST_BY_NAME_SUCCESS = 'FETCH_FORECAST_BY_NAME_SUCCESS'